### ISSUE TITLE
Install taskopen

### ISSUE THREAD

**Issue by Toraja** [Toraja/toybox#12]
## Summary
- https://github.com/jschlatow/taskopen
- This will create note associated with each task of taskwarrior and you can quickly open the note

## TODO
- [X] Install taskopen
- [ ] Create custom script for taskwarrior-tui that opens note for the selected task
- [ ] Configure the task note location
  - `~/.local/share/taskopen/notes/`
- [ ] Version track the config file

**Comment by Toraja** [comment]
### Install nim
`nim` is required to build taskopen.

```sh
# -y to suppress user prompt
curl https://nim-lang.org/choosenim/init.sh -sSf | sh -s -- '-y'
```

### Install taskopen
```sh
git clone --depth 1 --branch v2.0.0beta https://github.com/jschlatow/taskopen.git
cd taskopen
PATH=~/.nimble/bin:$PATH make PREFIX=/usr/local/
sudo make PREFIX=/usr/local/ install
```
